DROP TABLE IF EXISTS TB_PAUTA;
DROP TABLE IF EXISTS TB_SESSAO;
DROP TABLE IF EXISTS TB_VOTOS;

CREATE TABLE TB_PAUTA(
  ID_PAUTA INT AUTO_INCREMENT  PRIMARY KEY,
  NOME VARCHAR,
  STATUS BOOLEAN	
);

CREATE TABLE TB_SESSAO(
  ID_SESSAO INT AUTO_INCREMENT  PRIMARY KEY,
  DATA_ATIVACAO TIMESTAMP(9),
  DATA_DESATIVACAO TIMESTAMP(9),
  TEMPO_DURACAO INT,
  ID_PAUTA INT,
  foreign key (ID_PAUTA) references TB_PAUTA(ID_PAUTA)
);

CREATE TABLE TB_VOTOS(
  ID_VOTO INT AUTO_INCREMENT  PRIMARY KEY,
  VALOR BOOLEAN,
  CPF VARCHAR,
  ID_SESSAO INT,
  foreign key (ID_SESSAO) references TB_SESSAO(ID_SESSAO),
UNIQUE ( CPF,ID_SESSAO)
);

ALTER TABLE
TB_VOTOS
ADD CONSTRAINT VOTO_UNIQUE
UNIQUE ( CPF,ID_SESSAO);
